### ISSUE TITLE
API endpoints should be https only

### ISSUE THREAD

**Issue by paulschreiber** [opensupporter/osdi-docs#209]
To protect the privacy of the underlying data, all OSDI endpoints should be HTTPS-only.

The server(s) should be configured to send the appropriate HSTS header, and the sites should be added to the preload list.

cc @konklone

**Comment by konklone** [comment]
Yeah, big :+1:. I personally never want to be in a situation where I need to integrate a production system against an HTTP API, even if authentication also happens through an out-of-band token or HTTP Basic Auth.

If there's expected to be any use of these endpoints in CORS, then as @paulschreiber says, an [HSTS header](https://https.cio.gov/hsts/) is important. Preloading is likely to only be feasible if the base second-level domain implements the header and can specify an `includeSubDomains` policy for the entire domain, but if that's feasible then it should also be done.

It'll be much harder to migrate from HTTP->HTTPS later, so launching a new API is an important time to only support HTTPS.

**Comment by joshco** [comment]
The committee consensus is that we should have these two elements as security recommendations.  ie SHOULD, but not MUST.  

@paulschreiber   Would you be willing to generate a pull request (from our gh-pages branch) that lays out these recommendations?

If possible, that should include a short overview of how someone implements HSTS as it is not something people are generally familiar with.

**Comment by paulschreiber** [comment]
It's bad enough when a web _site_ uses HTTP instead of HTTPS. But a web service — especially one that transmit PII, as OSDI does — simply _must_ use HTTPS.

**Comment by paulschreiber** [comment]
I've checked out the gh-pages branch of your repository.

Where should I put the security recommendations? Should I edit an existing section? Or add a new one?

**Comment by j-ro** [comment]
On the main readme page I think, the index, add a section

**Comment by konklone** [comment]
Thanks for taking @paulschreiber's request to the committee, @joshco. I agree with @paulschreiber that for web services -- especially ones that transmit sensitive information -- it really ought to be a `MUST`. I hope the committee will continue to evaluate this, especially in light of the kind of information OSDI covers.

@paulschreiber Feel free to CC me on the PR for the recommendations once you've filed it, I'd love to chip in where I can.

**Comment by j-ro** [comment]
I'll say that while we do implement https, I don't think it should be a must. 

There are plenty of OSDI use cases where sensitive information is *not* being transmitted. For example, we're considering a blind post in #210, which would allow frontend javascript only implementations. When signing a petition and passing something like name an email, I'm not sure https is required. It's better, yes, but there are plenty upon plenty of webforms that collect that type of information in the clear.

Or, in another use case I've been thinking about, say you want to display a list of the latest signers to a petition, using javascript to make the call. In this non-authenticated scenario, it would return just maybe first names and states, so you could have a running feed of these folks on your page, updated in real time. Again, not necessary to implement https. Good, but not required.

I'd rather not rule out use cases we haven't seen, or make implementation harder by requiring certificates for servers, especially if folks are considering partial implementations where sensitive data is not transmitted. That's why a recommendation seems appropriate, and certainly an explanation that if you are passing sensitive data, you really should do https, for your user's sake.

**Comment by konklone** [comment]
> When signing a petition and passing something like name an email, I'm not sure https is required. It's better, yes, but there are plenty upon plenty of webforms that collect that type of information in the clear.

So I would argue that name and email is absolutely sensitive information. There are definitely plenty upon plenty of webforms that collect that information in the clear -- and all of them are irresponsibly configured.

> I'd rather not rule out use cases we haven't seen, or make implementation harder by requiring certificates for servers, especially if folks are considering partial implementations where sensitive data is not transmitted. That's why a recommendation seems appropriate, and certainly an explanation that if you are passing sensitive data, you really should do https, for your user's sake.

The fact that you and I may see sensitivity differently is itself a big argument for just encrypting everything. This is the stance [the US government has taken](https://https.cio.gov): that there simply is no such thing as insensitive web traffic, and that when you let people make judgment calls about what's sensitive and what's not, enough people will make [the wrong call](https://www.washingtonpost.com/blogs/the-switch/wp/2015/04/16/why-confidential-tips-to-the-government-may-not-be-confidential-after-all/). The US government took a [hard stance on "everything"](https://https.cio.gov/everything/) to eliminate the opportunity for those kind of mistakes, regardless of how annoying certificate installation may be today.

**Comment by j-ro** [comment]
I don't really disagree with you, I just don't think this belongs in the spec, that's all. I can think of web traffic we send that's not sensitive, but we encrypt everything anyway, because we believe it's the right thing to do. But that should be up to the system, not a specifications committee. If someone things they have a use case that they don't need encryption for, I don't think the spec should stand in their way.

**Comment by joshco** [comment]
We may not be as far apart as it might seem.  The committee discussion suggested that we do make support for HTTPS and HSTS SHOULD level requirements in the specification.
So we're definitely making a deliberate statement to push people in the direction of securing their implementations.

While I do agree that data like emails is sensitive personal information and it is good practice to send over secure channels, I think SHOULD is the right requirement level for HTTPS/HSTS at this time.

**Comment by joshco** [comment]
@paulschreiber Seems to me the place to create this recommendation text is alongside the encryption and authentication sections of the main doc (readme.md)
https://github.com/opensupporter/osdi-docs#encryption
