### ISSUE TITLE
Ticket tiers on events

### ISSUE THREAD

**Issue by j-ro** [opensupporter/osdi-docs#235]
opening an issues so I can tag my commits...

**Comment by j-ro** [comment]
updated for today's meeeting! We'll need to add in more once @shaisachs is done with the attendances part. (as in, if we go with donations and attendances, which seems to make sense, we'll be adding a donations link here on the events.md file)

**Comment by shaisachs** [comment]
Oh hi - sorry I didn't email about it, but actually the donations-to-attendances link should be included on the branch.  I added submissions into the bargain because I thought that might make sense in some cases.  (I can't actually imagine *charging* users to sign up to an email list, but I suppose it might be useful for something.)  No other resources seemed to make sense in this context - I thought about petitions but decided that charging for a petition signature was basically nonsense - so I think we're set here.

**Comment by j-ro** [comment]
Cool! The changes are on this branch? feature/ticketed-events?

**Comment by shaisachs** [comment]
Oh whoops - I forgot that I was pushing them to our fork of the repo: https://github.com/ngpvan/osdi-docs/tree/feature/ticketed-events

I don't have access to push to this repo, but I can do a remote PR or what-not.

**Comment by j-ro** [comment]
oh, cool, no prob. Let's talk about this one on the call. I was thinking more that events.md had a link to donations, which I guess it would have in addition. Do we need to cross link it with attendances though? Maybe the common link to the same event is enough? Maybe not, but setting up the link probably implies POSTing HAL, right?

Also, we probably want to update the record attendance helper to include donations as a possibility somehow, right? Or maybe not, maybe we just add a record donation helper, keep donations separate?

**Comment by j-ro** [comment]
fuller wire example here: https://github.com/opensupporter/osdi-docs/tree/feature/ticketed-events
