### ISSUE TITLE
OSDI documentation localizations and translations

### ISSUE THREAD

**Issue by bmenant** [opensupporter/osdi-docs#262]
Greetings from France!

A glance at the leaderships and the stakeholders of the OSDI made me wondering if the specifications could be of any help outside of the USA? 

Surely, many features discussed over here are also relevant all around the world. How about promoting these specifications abroad, finding foreign members and translating the documentation into other languages?

I’m currently working with a French non-profit to provide them with a comprehensive action toolset. The OSDI specifications might be of great help. We’ll see if it fits our needs and use cases.

**Comment by j-ro** [comment]
Hello @bmenant! Great to hear from you.

While we did take localization and internationalization into account when making the spec (we use given/family name instead of first/last name, for example, and we have fields for language spoken and whatnot), there's probably a lot more we can do. And certainly would love help translating docs.

So, I think we'd welcome your opinions and assistance! If you want to join us more than just working on github, like being on our weekly calls and voting on the spec, you can get started applying here: https://actionnetwork.org/forms/osdi-signup?

**Comment by sonyabea** [comment]
closed by committee 9/19/2018
