### ISSUE TITLE
RFC on extending Person resource for Organization use cases

### ISSUE THREAD

**Issue by schuyler1d** [opensupporter/osdi-docs#302]
Contra to #297 (OSDI Organizations Resource) enough of our use-cases around Organizations fit within a Person resource and are for links that are to Person resources that I would like to suggest we extend Person resource for Organizations.

First Use-Cases:
* Petition creators can be organizations
* Petition creators can be *people* -- *representing* an organization
* Petition targets can also be organizations, but also people representing an organization (e.g. Gov X Y Z for the state of XX)
* The same can be said for Donations, Canvassing (Canvassers can be representing an org), etc.

This is a rough draft with an interest to solicit thoughts on how we might do this:

## Extend Person with additional fields:

* `organization`: The human-readable name of the organization
* `organization_url`: link to the organization's home page (or local page on behalf of the org -- e.g. https://secure.actblue.com/donate/ms_jones_fr_q42017 vs. https://dougjonesforsenate.com/)
* `organization_logo_url`: link to a logo image.  This could also be an array in `organization_logo` with `width` and `height` and `type` (for "icon") values sorted by total area if people think this would be useful.
* `organization_fields`: corresponds to `custom_fields` for the person

## Interpretation of the Person record when an `organization` value is present:

* postal_addresses, phone_numbers, email_addresses, and profiles should be interpreted to be for the organization
* other fields should be interpreted to be for the person with the `{given,family,full}_name` listed if there is one.

Implementers supporting `organization` should understand the record as being wholly for an organization when there are no name fields.  If there are name fields, then the name is a person-as-proxy/representative for the organization.

Thoughts?

**Comment by j-ro** [comment]
Personally would like to see them separate. There is semantic value in keeping different things different. For example, petitions and forms are very similar but we have them separate anyway because it’s useful semantically.

**Comment by AaronSofaer** [comment]
I think that what this lacks as compared to having a separate Organization resource is that a persistent Organization object is linkful ("What are the objects associated with this Organization?") and associated with multiple Person resources, whereas the singular Organization-as-Person resource lacks the ability to say "What events are being hosted by Planned Parenthood, across their many Persons who are hosting the events?" and similar.

**Comment by AaronSofaer** [comment]
Whatever implementation of Organization we wind up going with, a `legal_status` or similar field (LLC, Sole Prop, 501c3, etc) would be nice.

**Comment by joshco** [comment]
Are you saying the expected use is going to include that there are a set of people resources, like josh, jason, aaron and skyler linked to another resource to represent an org (say OSDI) but that all of these resources are just people?  

When retrieving people objects, Organizations would be mixed in with people?
how does the linknaming work?

**Comment by schuyler1d** [comment]
I think the tension is that the places where I (and my use-cases) need it are places that are already classed as a Person type -- e.g. [petition.creator](https://opensupporter.github.io/osdi-docs/petitions.html#links)

If the spec can change those types to something that is a super-class of Person (Entity?) and accept an Organization type in those contexts, then.

The other end of that tension that some of you have alluded to is query calls, which you are describing as all things of a type must be returned from some API point.  I suppose joining types to api point queries is fair and adds simplicity, but otherwise, we could just say that Person-type records for an organization shouldn't be returned when querying people, and you can get (pure) Organization records from another api point /organizations or whatever.

However, in terms of places like petition.creator, etc, the JSON should be able to be a mixed record (or represent it some other way)

**Comment by joshco** [comment]
lets talk about this on tomorrow's call. I'd like to hear you walk through more of how you're really going to use it

**Comment by mpaquette1** [comment]
@schuyler1d  mentions some very common use cases in my experience, and FWIW we handle it much as he proposes, using person records and organization records interchangeably as donors or meeting attendees or whatever.  It's all just person records underneath, and we have a Company Name field in the person record and also a "contact type" field to distinguish a person record from an organization record.  (The list of possible person record types is up to the client, and can get specific: Individual, Company, Foundation, School District, Union Local, Media, Contractor, etc.)  Any org-specific fields (logo, legal status, etc) are treated as custom data depending on the client's needs.

So from my standpoint, if the Person resource added an Organization/Company Name and maybe a Record Type field, it would lower the friction between OSDI and thedatabank.  Beyond that, we like to be as flexible as possible so I'd advocate leaving most of the other stuff as custom.

To your question @joshco, we do allow linking the organization records to their members' records --other person records-- so that we can aggregate donations for reporting and other purposes: at a household level, or among a company of employees, or a team of peer-to-peer fundraisers.  A "relationship" resource typically links one "Primary" record (the organization/team leader's Person record) with "Secondary" record(s), persons who may or may not share an address or other data with the primary.  (Households often are linked as "Spouse and Spouse" rather than "Primary and Secondary" -- the client gets to define the relationships that are useful to them.)

**Comment by joshco** [comment]
Next steps
Sky to copy Person as Organization, modify attributes accordingly, show example of create petition with organization association

**Comment by AaronSofaer** [comment]
I think a unified resource will be adequate for Resistr/CTA Aggregator's purposes so long as the "fellow orgmate" links are part of the spec. I'm happy to see this moving forwards.

**Comment by sonyabea** [comment]
Closed by committee on 9/19/2018
